name: bluetooth
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_bluetooth_serial: ^0.4.0
  pdf: ^3.11.3
  printing: ^5.14.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  fl_chart: ^0.67.0
  share_plus: ^12.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/yigit.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/yigit.jpg"
